deploy:
  file: bintray.json
  key: $BINTRAY_KEY
  on:
    tags: true
  provider: bintray
  skip_cleanup: true
  user: pauldraper
git:
  depth: 1
script:
  - ls
  - make VERSION=$TRAVIS_TAG all bintray
